// Generated by CoffeeScript 1.4.0
(function() {
  var ExceptIO, encode, exceptioScriptTag, httpRequest, script, scripts, url;

  scripts = function() {
    return document.getElementsByTagName('script');
  };

  exceptioScriptTag = function() {
    var script;
    return ((function() {
      var _i, _len, _ref, _results;
      _ref = scripts();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        script = _ref[_i];
        if (/exceptio.js/.test(script.src)) {
          _results.push(script);
        }
      }
      return _results;
    })())[0];
  };

  httpRequest = function() {
    if (window.XMLHttpRequest) {
      return new XMLHttpRequest();
    } else if (window.ActiveXObject) {
      return new ActiveXObject("Microsoft.XMLHTTP");
    }
  };

  encode = function(obj) {
    var prop, values;
    values = (function() {
      var _results;
      _results = [];
      for (prop in obj) {
        _results.push("" + (encodeURIComponent(prop)) + "=" + (encodeURIComponent(obj[prop])));
      }
      return _results;
    })();
    return values.join("&");
  };

  url = function(application, apiKey) {
    return "https://except.io/applications/" + application + "/errors?api_key=" + apiKey;
  };

  ExceptIO = {
    apiKey: "",
    application: "",
    debug: false,
    environment: 'production',
    configure: function(apiKey, application, debug, environment) {
      this.apiKey = apiKey;
      this.application = application;
      this.debug = debug != null ? debug : false;
      this.environment = environment != null ? environment : 'production';
      return console.log('configuring', arguments);
    },
    log: function(exception, params, session, request_url) {
      var body, xhr;
      if (params == null) {
        params = {};
      }
      if (session == null) {
        session = {};
      }
      if (request_url == null) {
        request_url = window.location.href;
      }
      body = encode({
        error: {
          message: exception,
          backtrace: '',
          type: '',
          environment: this.environment,
          params: params,
          session: session,
          request_url: request_url
        }
      });
      if (this.debug) {
        return console.log(url(this.application), body);
      } else {
        xhr = httpRequest();
        xhr.open('POST', url(this.application, this.apiKey));
        xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        return xhr.send(body);
      }
    }
  };

  if (script = exceptioScriptTag()) {
    ExceptIO.configure(script.getAttribute('data-api-key'), script.getAttribute('data-application'), /true/.test(script.getAttribute('data-debug')));
  }

  window.ExceptIO = ExceptIO;

}).call(this);
